# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Pneumonia_Machine_Learning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pneumonia_Machine_Learning
  pod "Resolver"


  target 'Pneumonia_Machine_LearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pneumonia_Machine_LearningUITests' do
    # Pods for testing
  end

end
